# Generated by Django 2.2.1 on 2019-06-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textmessage', models.CharField(max_length=26)),
                ('number', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='WeblinkModel',
            fields=[
                ('weblink', models.CharField(max_length=250, null=True)),
                ('increment_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WifiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifiName', models.CharField(max_length=26)),
                ('wifiPass', models.CharField(max_length=28)),
                ('wifiAuth', models.CharField(max_length=8)),
            ],
        ),
    ]
