# Generated by Django 2.2.1 on 2019-06-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmodel',
            name='textmessage',
            field=models.CharField(max_length=250),
        ),
    ]
